---
# - name: Ensure MySQL users are present.
#   mysql_user:
#     name: "webaccess"
#     host: 0.0.0.0
#     password: secret
#     priv: "*.*:ALL,GRANT"
#     state: present
#     append_privs: "{{ item.append_privs | default('no') }}"
#     encrypted: "{{ item.encrypted | default('no') }}"
#   with_items: "{{ mysql_users }}"
#   no_log: true

#   # I ALSO HAVE TO ADD MY USER HERE, SAME USER I create in defaults/main.yml

#   ---
- name: Ensure MySQL users are present.
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    state: "{{ item.state | default('present') }}"
    append_privs: "{{ item.append_privs | default('no') }}"
    encrypted: "{{ item.encrypted | default('no') }}"
  with_items: "{{ mysql_users }}"
  no_log: true
